title: Pen and Paper
description: Ein einfaches Rollenspiel-System basierend auf Dungeons & Dragons® (D&D).

plugins:
- jekyll-remote-theme

# Theme options
remote_theme: pages-themes/leap-day@v0.2.0
